spring.application.name=dreamreach
# Cloud Deployment: Use the environment PORT if it exists, otherwise default to 8080 for local dev
server.port=${PORT:8080}

# Enable the H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Tell Hibernate to automatically create/update our tables based on our Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true