-- V13: Expand Character Schema to support D&D 2024 Mechanics and Gacha UI
ALTER TABLE character_template
ADD COLUMN hit_die_type INTEGER NOT NULL DEFAULT 8,
ADD COLUMN primary_stat VARCHAR(20) NOT NULL DEFAULT 'STR',
ADD COLUMN class_tags TEXT,
ADD COLUMN flavor_quips TEXT,
ADD COLUMN portrait_url VARCHAR(255);

ALTER TABLE player_character
ADD COLUMN current_hp INTEGER NOT NULL DEFAULT 10,
ADD COLUMN max_hp INTEGER NOT NULL DEFAULT 10,
ADD COLUMN current_mana INTEGER NOT NULL DEFAULT 0,
ADD COLUMN max_mana INTEGER NOT NULL DEFAULT 0,
ADD COLUMN spent_hit_dice INTEGER NOT NULL DEFAULT 0,
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'IDLE',
ADD COLUMN long_rest_end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN weapon_tier VARCHAR(20) NOT NULL DEFAULT 'BASIC',
ADD COLUMN armor_tier VARCHAR(20) NOT NULL DEFAULT 'BASIC';